#!/bin/bash


# total permitted number
n=$1; shift
[ -z "$n" ] && n=10

mkdir -p data

for p in 2; do
  for q in 3; do
    for r in 7 8 9; do
      c=0 # count existing files
      for i in data/cg_system_${p}-${q}-${r}*; do
        ((++c))
      done
      for i in $(seq $c $((n-1))); do
        ./ss_generator $p $q $r
      done
    done
  done
done

# ./run_cg_generation
# ./run_cg_visualization
